meta_title: "ResearchBored, save the web"
meta_description: "Save everything and close the tabs, find it again."
meta_image: "https://res.cloudinary.com/bdavidxyz-com/image/upload/v1641473825/rails/homeimage.png"
twitter_account: "@https://twitter.com/stuartwurtman"
